#!/bin/bash
# session-brief.sh — auto-generates a session brief to ~/inbox after every agent turn
# Called by Claude Code Stop hook. Silent — no stdout, errors to log only.
# Overwrites ONE file per session (identified by boot timestamp) so inbox never floods.

SESSION_FILE="$HOME/.session_start"
LOG="$HOME/.session_brief.log"
INBOX="$HOME/inbox"

# No session started → nothing to do
[ -f "$SESSION_FILE" ] || exit 0

SESSION_START=$(cat "$SESSION_FILE" | grep "^ts=" | cut -d= -f2)
SESSION_CRON=$(cat "$SESSION_FILE" | grep "^cron=" | cut -d= -f2)
SESSION_DATE=$(echo "$SESSION_START" | cut -c1-10)

[ -z "$SESSION_START" ] && exit 0

BRIEF_FILE="$INBOX/session-${SESSION_DATE}-brief.md"

# ── Git activity since session start ─────────────────────────────────────────
GIT_SECTION=""
while IFS= read -r -d '' repo; do
    repo_dir="$(dirname "$repo")"
    repo_name="$(basename "$repo_dir")"
    # Skip hidden dirs, venvs, node_modules
    echo "$repo_dir" | grep -qE "\.bun|envs|node_modules|\.local|cache" && continue
    commits=$(git -C "$repo_dir" log --oneline --after="$SESSION_START" 2>/dev/null | head -8)
    if [ -n "$commits" ]; then
        GIT_SECTION="${GIT_SECTION}\n**${repo_name}/**\n$(echo "$commits" | sed 's/^/  /')\n"
    fi
done < <(find "$HOME" -maxdepth 4 -name ".git" -type d -print0 2>/dev/null)

# ── Files modified since session start ───────────────────────────────────────
MODIFIED=$(find "$HOME" -newer "$SESSION_FILE" -type f \
    ! -path "*/.git/*" \
    ! -path "*/__pycache__/*" \
    ! -path "*/node_modules/*" \
    ! -path "*/.bun/*" \
    ! -path "*/.local/*" \
    ! -path "*/.claude/*" \
    ! -path "*/inbox/*" \
    ! -path "*/.session*" \
    ! -path "*/state/*.log" \
    ! -path "*/state/*.jsonl" \
    ! -path "*/cache/*" \
    ! -path "*/envs/*" \
    ! -path "*/.npm/*" \
    ! -path "*/.bybit/*" \
    ! -path "*/.hermes/*" \
    ! -name "*.log" \
    ! -name "*.jsonl" \
    ! -name "*.pyc" \
    2>/dev/null \
    | sed "s|$HOME/||" \
    | sort \
    | head -30)

FILE_COUNT=$(echo "$MODIFIED" | grep -c "." 2>/dev/null || echo 0)
[ "$MODIFIED" = "" ] && FILE_COUNT=0

# ── Cron change ───────────────────────────────────────────────────────────────
CRON_NOW=$(crontab -l 2>/dev/null | grep -v "^#" | grep -v "^$" | wc -l | tr -d ' ')
CRON_SECTION="${CRON_NOW} active jobs"
if [ -n "$SESSION_CRON" ] && [ "$SESSION_CRON" != "$CRON_NOW" ]; then
    DIFF=$((CRON_NOW - SESSION_CRON))
    [ "$DIFF" -gt 0 ] && CRON_SECTION="${CRON_NOW} active jobs  (+${DIFF} added this session)"
    [ "$DIFF" -lt 0 ] && CRON_SECTION="${CRON_NOW} active jobs  (${DIFF} removed this session)"
fi

# ── Skip brief if nothing happened ────────────────────────────────────────────
if [ -z "$GIT_SECTION" ] && [ "$FILE_COUNT" -eq 0 ]; then
    exit 0
fi

# ── Disk ──────────────────────────────────────────────────────────────────────
DISK=$(df -h "$HOME" | awk 'NR==2{print $4 " free (" $5 " used)"}')
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# ── Build brief ───────────────────────────────────────────────────────────────
mkdir -p "$INBOX"

{
echo "# Session Brief — ${SESSION_DATE}"
echo ""
echo "| | |"
echo "|---|---|"
echo "| **Session started** | ${SESSION_START} |"
echo "| **Last updated**    | ${NOW} |"
echo "| **Disk**            | ${DISK} |"
echo "| **Cron**            | ${CRON_SECTION} |"
echo ""

if [ -n "$GIT_SECTION" ]; then
echo "## Git Commits"
echo -e "$GIT_SECTION"
fi

if [ "$FILE_COUNT" -gt 0 ]; then
echo "## Files Modified (${FILE_COUNT})"
echo "$MODIFIED" | sed 's/^/- ~\//'
fi

echo ""
echo "---"
echo "*Auto-generated by session-brief.sh — updated after each agent turn*"
} > "$BRIEF_FILE"

exit 0
